// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/app_page.dart' as a0;
import 'app/guarded/report_page.dart' as a1;
import 'app/user/[id]_page.dart' as a2;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.MyHomePage(),
        ),
      ),
      RouteEntity(
        key: '/guarded/report',
        uri: Uri.parse('/guarded/report'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.UserPage(),
        ),
      ),
      RouteEntity(
        key: '/user/[id]',
        uri: Uri.parse('/user/[id]'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.UserDetailPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  guarded: (
    path: '/guarded',
    report: '/guarded/report',
  ),
  user: (
    path: '/user',
    $id: '/user/[id]',
  ),
);
